"""Data types for the fixed-question investigator guardrail."""

from __future__ import annotations

import pydantic


class ReconsiderVerdict(pydantic.BaseModel):
    """The investigator's judgement about the responder's original answer."""

    model_config = pydantic.ConfigDict(frozen=True, extra="forbid")

    score: float = pydantic.Field(ge=0.0, le=1.0)
    """0-1 confidence that the ORIGINAL answer was correct (higher = more likely correct)."""
    reasoning: str | None = None
    """Optional brief justification for the score."""


class ReconsiderTranscript(pydantic.BaseModel):
    """Single-turn transcript for one scored record."""

    model_config = pydantic.ConfigDict(frozen=True, extra="forbid")

    question: str
    """The fixed follow-up question put to the responder."""
    revised_output: str
    """The responder's full free-text reply to the follow-up."""
    revised_answer: str | None
    """Final answer extracted from the reply, or None when the tag was missing or malformed."""
    answer_changed: bool | None
    """Whether the revised answer differs from the original; None when extraction failed."""
    verdict: ReconsiderVerdict
    """The investigator's judgement about the original answer."""
    responder_token_count: float
    """Completion tokens generated by the responder."""
    investigator_token_count: float
    """Completion tokens generated by the investigator."""

    @property
    def total_token_count(self) -> float:
        """Total completion tokens across both models, used as the verification cost."""
        return self.responder_token_count + self.investigator_token_count
